
services:
  web:
    build: .
    command: gunicorn icecream.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis
    restart: always

  celery:
    build: .
    command: celery -A icecream worker --loglevel=info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

  flower:
    build: .
    command: celery -A icecream flower --port=5555
    ports:
      - "5555:5555"
    env_file: .env
    depends_on:
      - redis
